<?php
  include "libe.php";
  o_header('Messiah');
?>
<div id="content-wrapper"><div id="content">
<p>Messiah, written between August 22 and September 14, 1741, was first performed for charity in Dublin, at the New Music-hall in Fishamble Street in April and May of 1742.
A great success there, it was greeted in London the next year by the official hostility of the Bishop of London, who felt it inappropriate to hear actors and actresses (dissolute persons) uttering the sacred New Testament words in a public theater (Theatre Royal, Covent Garden).</p> 

<p>Until the Bishop died, in 1748, Messiah was performed only intermittently, and usually billed as “Mr. Handel’s Sacred Grand Oratorio”, lest the very word Messiah call forth the imprecations of priggish clergy.  It was not, in fact, performed in church until 1749, but in 1750 it became associated with the “Hospital for the Maintenance and Education of Exposed and Deserted Young Children”—the Foundling Hospital—where it was performed every year from that year until six weeks before Handel died, in 1759. Shortly thereafter, of course, the work literally became a cult. Alterations by musicians other than Handel (he had made many alterations in the music while he was still alive) continued to be made, and performances by ever-larger forces became the rule.  We can only wonder what Handel, who had something like 25 singers, including soloists, at the first Dublin performances, would have made of the Commemorative Performance of Messiah in Westminster Abbey in 1784, which featured a total of 267 performers!</p>

<p>We have just over 30 singers and soloists, and a small orchestra of modern instruments—considerably more forceful in sound than the instruments of Handel’s day—and will strive to make the drama, the excitement, and the human emotions of the text manifest in a clarity of line and texture which we believe is close to the effect of the original, certainly not in the same category as the sound of that monster production of 1784.</p>

<p>Most of us know “Messiah” as a vivid, dramatic depiction of the central story of Christianity: the birth of Jesus, his Crucifixion, his triumph over death, and his promise to his faithful followers, who will eventually be redeemed by faith.  “His yoke is easy, and his burthen is light”, says the choral text, and ultimately “He giveth us the victory in our Lord, Jesus Christ”.  And surely Handel, in that famous white heat of invention over some 20-plus days in the fall of 1741, had the Christian message of the Biblical text uppermost in his mind, pointing its message with melodies jagged (“He hath smashed them in pieces like a potter’s vessel” and smooth (“I know that my redeemer liveth”, lamenting (“He was despised and rejected”) and triumphant (“Hallalujah”).  But this may not be the entire story, or message, of Charles Jennens’ libretto for “Messiah”.</p>

<p>Recently I heard a fascinating lecture by Prof. Steve Nissenbaum (Emeritus, U.Mass Amherst, and a sometime teacher of history at UVM), which enlarged upon a theory posited by the Handel Scholar Ruth Smith, suggesting that “Messiah” really is intended to carry a second, contemporary political message.  In this reading, we remember that Jennens was part of the Jacobite faction of English politics hoping for the restoration of the Scottish Stuart monarchy (displacing the Germanic Hanoverian line of George II) and the replacement of George II’s corrupt Whig majority in the Commons by the opposition party. He thus chose Biblical verses, mostly from the Old Testament, which promised Zion (the Israelites, metaphorically the English) that soon “corruption” would end, and Zion would “arise, shine, for thy light is come”.  The cry of “Hallelujah” would be appropriate when this was achieved.</p>

<p>Of course the great irony in this subtext of “Messiah” is that George II chose, for whatever reason, to rise during the singing of the Hallelujah Chorus, arguably a chorus of rejoicing in the fall of George and his supporters!  Perhaps this is another reason for our modern practice of remaining seated during the chorus, listening carefully to Handel’s brilliant setting of the words, and, if well pleased, possibly rising at the end amidst warm applause.</p>

<p><b>“Historically Informed Performance Practice”, or, “Why is Messiah shorter now than it used to be?</b></p>

<p>After WWII the idea of “early music”. written before or during the period of Bach, Handel, Vivaldi and Telemann, developed rapidly. Instrument makers began to produce copies of instruments actually played by baroque and renaissance musicians. Recorders and one-keyed flutes, baroque-style oboes and bassoons, harpsichords copied from  surviving baroque instruments, and violins, violas and cellos with gut strings and their original structural features restored, all multiplied and were taken up by increasing numbers of modern players.</p>

<p>At the same time, musicologists and scholarly performers pursued an intensive study of early treatises and methods about how this “early music”should be played-- what did the written notation really mean to contemporaries who turned it into stylish performances? From the 1950s and ‘60s on, then, player-scholars worked assiduously in libraries, and gradually the “period instruments” themselves also “taught” players what could be done efficiently and effectively. Some of the hidden messages of notation and instruments were discovered, although not always understood in exactly the same ways by all.</p>

<p>One conclusion of all this study was that tempi common in 18th-century music were probably faster than those we had become accustomed to in the 20th century. Another conclusion stressed the dance-related nature of much orchestral and operatic music, The issue of scale and balance in baroque music, especially of how many players and singers should be involved in works like Bach’s B-Minor Mass or Handel’s Messiah, was argued at length. One has only to listen to the “best” recordings of both these masterworks made prior to the early ‘60s, and compare them with recent versions by “period-instrument” forces, to realize that a revolution in style and sound has occurred. We now hear the textures and phrasing of baroque orchestral and choral music differently. The idea of a Messiah utilizing a thousand singers and players is now regarded as ridiculous by most of us, however common such a performance would have been in the 19th-century. Yet by the same token,  when singing Handel’s choral works, one should never think in Bachian terms—there is nothing particularly “inauthentic” about performing the great B-Minor with instruments one-to-a-part, and very few singers, but that would not do at all for Messiah, which Handel would not have recognized in that form.</p>

<p>So our Messiah will be sung and played by about 40 of us, its tempi will be on the quicker side (but not too quick, we hope), its texture will be open, transparent, at times airy although not devoid of seriousness and nobility, we trust.  We don’t claim this as the only way to do Messiah, but we do claim it as ONE of the better ways to do it, and the one which we have grown to like, by and large. Besides, however it is performed, Messiah’s genius will out.
</p>
</div></div>
<?php
  o_footer();
?>